version: "3.7"

services:
  application:
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}${_Values_server_arch}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    command: ["-Xmx${_Values_resources_requests_memory}"]

    healthcheck:
      test: "curl -f http://localhost:${_Values_service_port}/actuator/health || exit 1"
      interval: 5s
      timeout: 10s
      retries: 5
    volumes:
      - tmp:/tmp
      - applogs:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: "Europe/Berlin"
      quarkus.http.port: "${_Values_service_port}"
      quarkus.http.io-threads: "20"

      #security
      security.authentication.enabled: "false"

      #jaeger
      quarkus.jaeger.service-name: "callee-service"

      quarkus.jaeger.endpoint: "http://host.docker.internal:14268/api/traces"
      quarkus.jaeger.sampler-type: "probabilistic"
      quarkus.jaeger.sampler-param: "1"
      quarkus.jaeger.propagation: "b3"

      #log levels
      quarkus.log.level: "INFO"
      quarkus.log.category."org.goafabric".level: "INFO"
      quarkus.log.category."org.flywaydb.core".level: "INFO"
      quarkus.log.category."org.hibernate".level: "INFO"

  nginx:
    container_name: ${_Values_root_name}-nginx
    image: nginx:1.22.1
    restart: 'no'
    ports:
      - 8080:80
      - 444:443
    networks:
      - ${_Values_root_name}-net
    volumes:
      - ./nginx/nginx${_Values_nginx_oidc}.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/ssl/
    depends_on:
      application:
        condition: service_started

volumes:
    tmp:
    applogs:

networks:
  callee-service-net:
    driver: bridge